spring:
  servlet:
    multipart:
      max-file-size: 100000MB #设置单个上传文件的最大大小。
      max-request-size: 500000MB  # 设置整个 HTTP 请求的最大大小，即一次请求中所有上传文件的总和不能超过该值。
  data:
    # redis配置
    redis:
      cluster:
        nodes:
      # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      password: 497903
      # Redis服务器连接密码（默认为空）
      # password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/student_class_teacher?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 497903
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            connect-timeout: 9999999
            read-timeout: 99999999
    sentinel:
      transport:
        dashboard: localhost:8080 #在需要管理的微服务配置
      eager: true # 由加载变为快速加载
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: task-service
server:
  port: 8020

#开启兜底返回
feign:
  sentinel:
    enabled: true

sa-token:
  is-share: true  # 必须开启
  is-concurrent: true